import { defineConfig } from "tsup";

/**
 * Bundle the client into one ESM chunk.
 *
 * Why: `tsc` + `moduleResolution: "Bundler"` emits extensionless relative
 * imports, and Node's ESM loader REQUIRES explicit `.js` extensions. Bundling
 * resolves every specifier at build time, so `dist/` is valid Node ESM
 * regardless of source style. The generated Codama output (regenerated by
 * `pnpm --filter @riprap/pool codegen`) gets inlined; runtime deps stay
 * external (resolved from consumers' node_modules). Type declarations are
 * emitted separately by `tsc -p tsconfig.build.json` (see `build`).
 */
export default defineConfig({
  entry: { index: "src/index.ts" },
  format: ["esm"],
  target: "es2022",
  outDir: "dist",
  sourcemap: true,
  clean: true,
  keepNames: true,
  external: ["@solana/kit", "@solana-program/token", "@solana/program-client-core"],
});
