[toolchain]
anchor_version = "1.2.0"
solana_version = "3.1.10"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hanse = "hanseP4mdA6Df5TXkd3cDLKPaFqzE4PNJAGKkkvgqav"
pool = "PuuLXN4dNzoZ363h93WZi76NHwbH2AZcafKUqjGgdkf"

[programs.devnet]
hanse = "hanseP4mdA6Df5TXkd3cDLKPaFqzE4PNJAGKkkvgqav"
pool = "PuuLXN4dNzoZ363h93WZi76NHwbH2AZcafKUqjGgdkf"

[programs.mainnet]
hanse = "hanseP4mdA6Df5TXkd3cDLKPaFqzE4PNJAGKkkvgqav"
pool = "PuuLXN4dNzoZ363h93WZi76NHwbH2AZcafKUqjGgdkf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm --filter @riprap/tests test"

[hooks]
