import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

/**
 * Static manifest generation for videos/.
 *
 * Remotion's webpack bundler needs static imports (no runtime directory
 * scanning), so every command (build/lint/test/studio/render) first
 * regenerates src/videos.gen.ts from the videos/ tree. The file is
 * gitignored: CI regenerates it from the tracked dirs alone.
 */

export interface VideoEntry {
  slug: string;
  /** Import path relative to src/videos.gen.ts. */
  importPath: string;
}

const SLUG_RE = /^[a-z][a-z0-9-]*$/;
/** Reserved dirs: the scaffold template is not a registrable video. */
const SKIP_DIRS: Record<string, true> = { _template: true };

const HEADER = `// GENERATED by \`pnpm --filter @riprap/remotion sync\` — do not edit.
// Regenerated from apps/remotion/videos/ on every build/lint/test/studio/
// render run. Local video dirs are gitignored; CI only sees the tracked ones.`;

export function scanVideos(videosDir: string): VideoEntry[] {
  if (!existsSync(videosDir)) return [];
  const entries: VideoEntry[] = [];
  const errors: string[] = [];
  for (const ent of readdirSync(videosDir, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    if (SKIP_DIRS[ent.name]) continue;
    // Dirs starting with "_" are system/tracked dirs (e.g. _example);
    // author-created videos must be kebab-case.
    if (!ent.name.startsWith("_") && !SLUG_RE.test(ent.name)) {
      errors.push(`'${ent.name}' is not kebab-case (expected e.g. my-video)`);
      continue;
    }
    const hasIndex = ["index.ts", "index.tsx"].some((f) =>
      existsSync(path.join(videosDir, ent.name, f)),
    );
    if (!hasIndex) continue; // assets-only or work-in-progress dir
    entries.push({ slug: ent.name, importPath: `../videos/${ent.name}/index` });
  }
  if (errors.length > 0) {
    throw new Error(`apps/remotion videos — invalid directory names: ${errors.join("; ")}`);
  }
  return entries.sort((a, b) => a.slug.localeCompare(b.slug));
}

function ident(slug: string): string {
  return `video_${slug.replace(/-/g, "_")}`;
}

export function renderManifest(entries: VideoEntry[]): string {
  const imports = entries
    .map((e) => `import { video as ${ident(e.slug)} } from "${e.importPath}";`)
    .join("\n");
  const items = entries.map((e) => `  ${ident(e.slug)},`).join("\n");
  return `${HEADER}
import type { VideoDefinition } from "./framework/video";
${imports}

export const videos: VideoDefinition[] = [
${items}
];
`;
}

const TW_HEADER = `// GENERATED by \`pnpm --filter @riprap/remotion sync\` — do not edit.
// Tailwind class manifest for videos/. The videos/ tree is gitignored, so
// Tailwind v4 auto source detection never scans video scenes — utilities
// used only there would silently not generate (unstyled/blank frames).
// This file re-exposes every candidate class under src/, which IS scanned.
// Intentionally NOT gitignored; regenerated on every sync.`;

/** Tokens that could be Tailwind utilities: must carry a dash, bracket, or slash. */
const TW_TOKEN_RE = /[A-Za-z0-9_\-[\]\\/:.%]+/g;
const isTwCandidate = (tok: string): boolean => /^-?[A-Za-z]/.test(tok) && /[-[\]\\/]/.test(tok);

function walkSources(dir: string, out: string[]): void {
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      walkSources(p, out);
    } else if (/\.(ts|tsx)$/.test(ent.name)) {
      out.push(readFileSync(p, "utf8"));
    }
  }
}

/**
 * Every Tailwind candidate class used anywhere under videos/ — including
 * _example/_template and index-less dirs — so the generated manifest
 * covers all scenes, not just registered videos.
 */
export function collectTwClasses(videosDir: string): string[] {
  if (!existsSync(videosDir)) return [];
  const sources: string[] = [];
  walkSources(videosDir, sources);
  const classes = new Set<string>();
  for (const src of sources) {
    for (const tok of src.match(TW_TOKEN_RE) ?? []) {
      if (isTwCandidate(tok)) classes.add(tok);
    }
  }
  return [...classes].sort();
}

export function renderTwClassesFile(classes: string[]): string {
  return `${TW_HEADER}
export const VIDEO_TW_CLASSES =
  ${JSON.stringify(classes.join(" "))};
`;
}
export function sync(
  videosDir: string,
  outFile: string,
  twClassesFile: string,
): { count: number; slugs: string[]; changed: boolean } {
  const entries = scanVideos(videosDir);
  const next = renderManifest(entries);
  const nextTw = renderTwClassesFile(collectTwClasses(videosDir));
  const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
  const prevTw = existsSync(twClassesFile) ? readFileSync(twClassesFile, "utf8") : null;
  if (prev !== next) {
    mkdirSync(path.dirname(outFile), { recursive: true });
    writeFileSync(outFile, next);
  }
  if (prevTw !== nextTw) {
    mkdirSync(path.dirname(twClassesFile), { recursive: true });
    writeFileSync(twClassesFile, nextTw);
  }
  return {
    count: entries.length,
    slugs: entries.map((e) => e.slug),
    changed: prev !== next || prevTw !== nextTw,
  };
}
