/**
 * Regenerates the blurb page's brand-kit lockup + avatar from the SAME
 * sources as favicon.svg / mark.svg / wordmark.svg — the kit's ring
 * geometry (RING_SEEDS, GAP_INDEX=3, BLUE_INDEX=2, stone.ts family) and
 * the HarfBuzz-outlined wordmark paths in public/brand/wordmark.svg
 * (the previous lockup/avatar were the pre-ring generation and are gone).
 *
 * Outputs (all under apps/landing/public/brand/):
 *   avatar.svg / avatar.png   — the settled ring, tight crop, transparent
 *   lockup-horizontal.svg / lockup-horizontal.png — ring + wordmark at the
 *     LogoLockup ratios (mark = wordmark-em × 1.35, gap = 12px at 38px mark)
 *
 * Run: pnpm dlx tsx apps/landing/scripts/generate-brand-assets.mts
 * (PNGs rasterized via rsvg-convert, transparent, verified with magick)
 *
 * Hex values are inherent to static assets (no CSS cascade); they mirror
 * tokens.css: stone #A7ADB3, accent #3E7CA6, ink #F2EFE8 (dark-mode ink
 * baked into wordmark.svg — the lockup inherits each sub-asset's palette).
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import * as path from "node:path";
import {
  BLUE_INDEX,
  GAP_INDEX,
  RING_SEEDS,
  slotPosition,
  stonePoints,
  stoneRotation,
} from "@riprap/ui";

const STONE_SCALE = 0.55; // identical to Logomark / favicon / mark.svg
const STONE = "#A7ADB3";
const ACCENT = "#3E7CA6";
const INK = "#F2EFE8";

// ── the settled ring, favicon-identical geometry ────────────────────────────

function ringStones(): string[] {
  const stones: string[] = [];
  for (let slot = 0; slot < 8; slot++) {
    if (slot === GAP_INDEX) continue; // the open slot — open membership
    const p = slotPosition(slot);
    const rot = stoneRotation(RING_SEEDS[slot]);
    const pts = stonePoints("S", RING_SEEDS[slot])
      .map((pt) => `${(pt.x * STONE_SCALE).toFixed(2)},${(pt.y * STONE_SCALE).toFixed(2)}`)
      .join(" ");
    stones.push(
      `  <polygon transform="translate(${p.x.toFixed(2)} ${p.y.toFixed(2)}) rotate(${rot.toFixed(2)})" points="${pts}" fill="${slot === BLUE_INDEX ? ACCENT : STONE}"/>`,
    );
  }
  return stones;
}

// ── avatar.svg — the ring at a tight crop (ring ink y≈4..92 in the 96 box) ──

const AVATAR_VIEWBOX = "3 3 90 90"; // 3px margin around the ring ink
const avatarSvg = `<!-- Riprap avatar — the settled ring, avatar crop. GENERATED by scripts/generate-brand-assets.mts from the kit's ring layout (same seeds/gap/blue as favicon.svg and mark.svg); do not hand-edit. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${AVATAR_VIEWBOX}" role="img" aria-label="Riprap">
${ringStones().join("\n")}
</svg>
`;
writeFileSync(path.resolve(import.meta.dirname, "../public/brand/avatar.svg"), avatarSvg);

// ── lockup-horizontal.svg — ring + the current wordmark, LogoLockup ratios ──

// The wordmark's outlined glyphs live in wordmark.svg as one path with its
// own viewBox ("47 68.6 258.4 91.4", 100px em). Compose at LogoLockup's
// ratios: mark 96, wordmark em 96/1.35 = 71.11, gap 12px*(96/38) = 30.32.
const WORDMARK_SRC = readFileSync(
  path.resolve(import.meta.dirname, "../public/brand/wordmark.svg"),
  "utf8",
);
const wordmarkPath = WORDMARK_SRC.match(/<path fill="#f2efe8" d="([^"]+)"/)?.[1];
if (wordmarkPath === undefined) throw new Error("wordmark.svg: outlined path not found");

const WM_EM = 96 / 1.35; // 71.11
const WM_SCALE = WM_EM / 100; // 0.7111
const GAP = 12 * (96 / 38); // 30.32 — LogoLockup's --riprap-space-sm, scaled
const WM_BOX = { x: 47, y: 68.6, w: 258.4, h: 91.4 };
const LOCK_W = Math.round(96 + GAP + WM_BOX.w * WM_SCALE); // 310
// align the wordmark's ink-band center to the mark's center (y=48)
const WM_TX = 96 + GAP + (WM_BOX.w * WM_SCALE) / 2 - WM_SCALE * (WM_BOX.x + WM_BOX.w / 2);
const WM_TY = 48 - WM_SCALE * (WM_BOX.y + WM_BOX.h / 2);

const lockupSvg = `<!-- Riprap lockup, horizontal — the settled ring + the wordmark, at the LogoLockup ratios (mark 96, gap ${GAP.toFixed(2)}, wordmark em ${WM_EM.toFixed(2)}). GENERATED by scripts/generate-brand-assets.mts (ring from the kit's layout, wordmark path from wordmark.svg); do not hand-edit. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${LOCK_W} 96" role="img" aria-label="riprap">
${ringStones().join("\n")}
  <g transform="translate(${WM_TX.toFixed(2)},${WM_TY.toFixed(2)}) scale(${WM_SCALE.toFixed(4)})">
    <path fill="${INK.toLowerCase()}" d="${wordmarkPath}"/>
  </g>
</svg>
`;
writeFileSync(
  path.resolve(import.meta.dirname, "../public/brand/lockup-horizontal.svg"),
  lockupSvg,
);

// ── PNG rasterization (transparent, rsvg-convert; magick verifies) ─────────

function rasterize(svgFile: string, pngFile: string, width: number, height: number) {
  const svg = path.resolve(import.meta.dirname, `../public/brand/${svgFile}`);
  const png = path.resolve(import.meta.dirname, `../public/brand/${pngFile}`);
  execFileSync("rsvg-convert", ["-w", String(width), "-h", String(height), "-o", png, svg], {
    stdio: "pipe",
  });
  execFileSync("magick", ["identify", png], { stdio: "pipe" }); // fails unless rasterized
  console.log(`${pngFile}: ${width}x${height}`);
}

rasterize("avatar.svg", "avatar.png", 512, 512);
rasterize("lockup-horizontal.svg", "lockup-horizontal.png", LOCK_W * 2, 192);
console.log("brand assets regenerated: avatar + lockup (svg + png)");
