/**
 * Generates apps/landing/public/favicon.svg from the kit's ring layout —
 * the favicon is the settled Logomark, byte-for-byte the same geometry
 * (slot positions, seeds, gap, blue stone) as the in-app component.
 *
 * Run: pnpm dlx tsx apps/landing/scripts/generate-favicon.mts
 *
 * Hex values are inherent to a static asset (no CSS cascade in a favicon);
 * they mirror tokens.css: stone #A7ADB3, accent #3E7CA6.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  BLUE_INDEX,
  GAP_INDEX,
  RING_SEEDS,
  slotPosition,
  stonePoints,
  stoneRotation,
  STONE_SIZES,
} from "@riprap/ui";

const VIEWBOX = 96;
const STONE_SCALE = 0.55; // identical to Logomark

const stones: string[] = [];
for (let slot = 0; slot < 8; slot++) {
  if (slot === GAP_INDEX) continue; // the open slot — open membership
  const p = slotPosition(slot);
  const rot = stoneRotation(RING_SEEDS[slot]);
  const pts = stonePoints("S", RING_SEEDS[slot])
    .map((pt) => `${(pt.x * STONE_SCALE).toFixed(2)},${(pt.y * STONE_SCALE).toFixed(2)}`)
    .join(" ");
  stones.push(
    `  <polygon transform="translate(${p.x.toFixed(2)} ${p.y.toFixed(2)}) rotate(${rot.toFixed(2)})" points="${pts}" fill="${slot === BLUE_INDEX ? "#3E7CA6" : "#A7ADB3"}"/>`,
  );
}

const svg = `<!-- Riprap favicon — the ring (settled). GENERATED by scripts/generate-favicon.mts; do not hand-edit. 7 grey stones, one open slot, one harbor-blue newest member. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${VIEWBOX} ${VIEWBOX}" role="img" aria-label="Riprap">
${stones.join("\n")}
</svg>
`;

writeFileSync(resolve(import.meta.dirname, "../public/favicon.svg"), svg);
console.log(`favicon.svg written: ${stones.length} stones`);
console.log(`stone width source: S=${STONE_SIZES.S}px @ scale ${STONE_SCALE}`);
