// GENERATED by `pnpm --filter @riprap/remotion sync` — do not edit.
// Tailwind class manifest for videos/. The videos/ tree is gitignored, so
// Tailwind v4 auto source detection never scans video scenes — utilities
// used only there would silently not generate (unstyled/blank frames).
// This file re-exposes every candidate class under src/, which IS scanned.
// Intentionally NOT gitignored; regenerated on every sync.
export const VIDEO_TW_CLASSES =
  "data-num flex-col font-mono gap-10 gap-12 gap-14 gap-4 h-full items-baseline items-center m-0 p-12 riprap/ui scenes/ text-3xl text-body text-white/40 tracking- w-[420px] w-[720px]";
