name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run -r --filter "./packages/*" build

      - name: Build
        run: pnpm run -r --filter "./apps/landing" build
        env:
          # https://github.com/actions/runner-images/issues/70
          VITE_VCS_REF: ${{ github.sha }}
          NODE_ENV: production
          VITE_N8N_WEBHOOK_URL: ${{ vars.PUBLIC_N8N_WEBHOOK_URL }}

      - name: Deploy to external repository
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./apps/landing/dist
          cname: riprap.xyz
